### PR TITLE
fix timing calculation

### PR DESCRIPTION
**Pull request by snova-amitk**

### CODE REVIEW

**Review by snova-rodrigom — APPROVED** [review]
tested locally with 1k requests and 29 concurrent requests. @snova-amitk could you do a final merge with main please? thanks!

**Comment by snova-amitk** [comment]
@snova-rodrigom : Did the merge, if you could please check this works? Thanks!

**Comment by snova-rodrigom** [comment]
hey @snova-amitk could you try again please? I can't see the recent changes coming from Michael's PR in notebook

**Comment by snova-amitk** [comment]
@snova-rodrigom Yes this calculation is right.

**Pull request closed without merging**
