### PR TITLE
Removal/Langgraph ekr app and dependency removal

### PR DESCRIPTION
**Pull request by snova-codym**
Removing until required by a collaborative agent kit is created.

### CODE REVIEW

**Comment by snova-petrojm** [comment]
Cody, can you also remove enterprise_knowledge_retriever/notebooks/rag_langraph.ipynb? Thanks

**Comment by snova-petrojm** [comment]
Thanks, Cody. One more thing. Could you please remove reference to LangGraph in EKR README? Thanks

**Comment by snova-codym** [comment]
No problem, @snova-petrojm.  Good catch.

**Review by snova-petrojm — APPROVED** [review]
LGTM, thanks @snova-codym . Note I did a minor modif to  EKRREADME (one of the bash script wasn't displayed properly)

**Pull request merged**
